export:
  folder: custom
langcode: es
_core:
  default_config_hash: YS8SFNy6Qff2UEsQ5zXWEj-ABeRS-jCgcHJrXHJhtJ0
profile:
  machine_name: nica_portal
  name: 'NICA Portal'
  description: 'Somos El Cambio'
